HOSTS:
  centos8-64:
    docker_cmd:
      - "/sbin/init"
    image: centos:8
    platform: el-8-x86_64
    packaging_platform: el-8-x86_64
    docker_image_commands:
      - cp /bin/true /sbin/agetty
      - dnf install -y crontabs initscripts iproute openssl tar wget
    hypervisor: docker
    roles: []
