HOSTS:
  opensuse15-64:
    docker_cmd: '["/usr/lib/systemd/systemd", "--system"]'
    image: opensuse/leap:15
    platform: sles-15-x64
    packaging_platform: sles-15-x64
    docker_image_commands:
      - zypper --non-interactive --no-gpg-checks install wget gzip
      - wget https://yum.puppet.com/puppet6-release-sles-15.noarch.rpm
      - zypper --non-interactive --no-gpg-checks install puppet6-release-sles-15.noarch.rpm
      - zypper --non-interactive --no-gpg-checks install puppet-agent
    hypervisor: docker
    roles: []
